# Generated by Django 2.2.6 on 2019-10-29 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numInterno', models.IntegerField()),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('estado', models.CharField(default='Disponible', max_length=20)),
                ('ubicacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numTarjeta', models.IntegerField()),
                ('fechaVenc', models.DateField()),
                ('saldo', models.IntegerField()),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaArriendo', models.DateField(auto_now_add=True)),
                ('horaInicio', models.DateTimeField(auto_now_add=True)),
                ('horaTermino', models.DateTimeField(auto_now=True)),
                ('precio', models.IntegerField()),
                ('metodoPago', models.CharField(default='Tarjeta Credito', max_length=20)),
                ('calificacion', models.IntegerField()),
                ('bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bicicleta')),
            ],
        ),
    ]
